# Generated by Django 5.0.7 on 2024-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='blur',
            field=models.ImageField(default=1, upload_to='blur/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='colorize',
            field=models.ImageField(default=1, upload_to='colorize/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='distortion',
            field=models.ImageField(default=1, upload_to='distortion/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='sketch',
            field=models.ImageField(default=1, upload_to='sketch/'),
            preserve_default=False,
        ),
    ]
