# Generated by Django 5.0.7 on 2024-08-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_images_blur_images_colorize_images_distortion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='blur',
        ),
        migrations.RemoveField(
            model_name='images',
            name='cartoonized',
        ),
        migrations.RemoveField(
            model_name='images',
            name='colorize',
        ),
        migrations.RemoveField(
            model_name='images',
            name='distortion',
        ),
        migrations.RemoveField(
            model_name='images',
            name='sketch',
        ),
        migrations.AddField(
            model_name='images',
            name='filtered',
            field=models.ImageField(default=1, upload_to='filtered/'),
            preserve_default=False,
        ),
    ]
