# Generated by Django 5.0.7 on 2024-08-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_images_blur_remove_images_cartoonized_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('upscaled_video', models.FileField(upload_to='upscaled_videos/')),
            ],
        ),
    ]
